package com.ejemplo.backend.model;
// Generated 5/05/2018 05:13:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pendiente generated by hbm2java
 */
@Entity
@Table(name="pendientes"
    ,catalog="databasependientes"
)
public class Pendiente  implements java.io.Serializable {


     private Integer id;
     private String descripcion;

    public Pendiente() {
    }

    public Pendiente(String descripcion) {
       this.descripcion = descripcion;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


